import type { ActionKind as PricedAction } from '../../tables'
import { DEFENSES } from '../../lists'
import type { Action, ActionDraft, ActionKind, AttackAction, ReactionAction, ReactionKind, RootAction } from '../types'

// What kind of thing each action is. `type` is combat.tex "Reactions": a
// reaction is taken on someone else's turn and only in answer to one of the
// kinds it `reactsTo`. `price` names the row of ACTION_COSTS that is its
// whole cost; null where the price is the declaration's to say (a strike
// costs what its weapon row and variation cost).
export type ActionDef<K extends ActionKind = ActionKind> = {
  label: string
  // what the action is called as a thing done, where that differs from the
  // label ("cancel the shot")
  noun?: string
  type: 'action' | 'reaction'
  price: PricedAction | null
  reactsTo: readonly ActionKind[]
  // whether a die commits the action; one without is committed by paying.
  // A move is the exception `needsDie` makes: difficult terrain
  // puts a Balance test on it. On a reaction, whether it is a test of its
  // own, thrown with the root's die.
  die: boolean
  // combat.tex "Interruption": "If the character is in the middle of an
  // action that is not movement, it must interrupt itself in order to use a
  // reaction" — a movement goes on while its actor answers what it drew.
  // Every action's opportunity attacks are fought before its effect lands;
  // a move's along its path (rules/move.ts), and a strike's are its
  // flankers'.
  movement?: true
  // whether the declaration is aimed at someone the actor picks; a cast
  // only when its spell has an effect for a target (rules/cast.ts
  // `isTargeted`)
  targeted?: true
  // never declared by a player: made by another action's effect, so it has
  // no option of its own (rules/options.ts)
  generated?: true
  // the declared fields that tell two options of the kind apart, each with
  // the value it reads as when left out
  identity?: Partial<Omit<Extract<ActionDraft, { kind: K }>, 'kind'>>
}

export const ACTIONS = {
  // combat.tex "Strike"
  strike:      { label: 'strike',       type: 'action',   price: null,          reactsTo: [],         die: true, targeted: true, identity: { grab: false } },
  // combat.tex "Accuracy", "Shoot"
  shoot:       { label: 'shoot',        noun: 'shot',  type: 'action',   price: null,          reactsTo: [],         die: true, targeted: true },
  // combat.tex "Explosions": no test of the attacker's — "the DL of the
  // explosion is equal to the shooting skill", and it is the reactors who
  // roll; opened by a throw, a cast or a detonation, never declared
  explosion:   { label: 'explosion',    type: 'action',   price: null,          reactsTo: [],         die: false, generated: true },
  // combat.tex "Explosions": the explosion going off, generated by it once
  // the escapes are walked; nobody answers it
  blast:       { label: 'blast',        type: 'action',   price: null,          reactsTo: [],         die: false, generated: true },
  // spells.tex "Casting spells": the caster's test against the spell's DL
  cast:        { label: 'cast',         noun: 'spell', type: 'action',   price: null,          reactsTo: [],         die: true, targeted: true },
  // a held spell fired again without the casting test (the table's ruling)
  fireAgain:   { label: 'fire again',   type: 'action',   price: null,          reactsTo: [],         die: false, identity: { key: '' } },
  // spells.tex "Telepathic Link": a target's test against a spell worked
  // through a link, opened by the cast; nobody answers it
  spellTest:   { label: 'spell test',   type: 'action',   price: null,          reactsTo: [],         die: true, generated: true },
  // combat.tex "Movement"
  move:        { label: 'move',         type: 'action',   price: null,          reactsTo: [],         die: false, movement: true },
  // combat.tex "Defend": "There are four types of defense: Evade, Evasive
  // Jump, Intercept, and Block." "Evade: ... This can be used to avoid
  // being trampled" — a move whose path comes into the evader.
  evade:       { label: 'evade',        type: 'reaction', price: 'evade',       reactsTo: ['strike', 'move'], die: false },
  // combat.tex "Crash": standing firm against the mover, +3 to the Force
  brace:       { label: 'brace',        type: 'reaction', price: 'brace',       reactsTo: ['move'],   die: false },
  evasiveJump: { label: 'evasive jump', type: 'reaction', price: 'evasiveJump', reactsTo: ['strike'], die: false },
  block:       { label: 'block',        type: 'reaction', price: 'block',       reactsTo: ['strike'], die: false, identity: { weaponKey: '', attack: '' } },
  intercept:   { label: 'intercept',    type: 'reaction', price: 'intercept',   reactsTo: ['strike'], die: false, identity: { weaponKey: '', attack: '', advance: false } },
  // combat.tex "Reflex": "Evasion" and "Guard", the two reactions to a shot
  evasion:     { label: 'evasion',      type: 'reaction', price: 'reflex',      reactsTo: ['shoot'],  die: false, identity: { stay: false } },
  guard:       { label: 'guard',        type: 'reaction', price: 'guard',       reactsTo: ['shoot'],  die: false, identity: { weaponKey: '', attack: '' } },
  // combat.tex "Avoiding an Explosion": "Spend 3 AP and make a reflex skill
  // test against the DL of the explosion"
  avoidExplosion: { label: 'avoid explosion', type: 'reaction', price: 'avoidExplosion', reactsTo: ['explosion'], die: true },
  // combat.tex "Opportunity Attack", "Flanking", "Follow": priced by the
  // action each opens when the root resolves
  opportunityAttack: { label: 'opportunity attack', type: 'reaction', price: null, reactsTo: ['strike', 'move'], die: false, identity: { at: null } },
  // a held spray aimed anew in answer to the same triggers, priced by the
  // fireAgain it opens
  retarget:    { label: 'retarget',     type: 'reaction', price: null,          reactsTo: ['strike', 'move'], die: false, identity: { key: '', at: null } },
  // combat.tex "Coordinated Shots": priced by the shot it opens
  joinShot:    { label: 'join shot',    type: 'reaction', price: null,          reactsTo: ['shoot'],  die: false },
  follow:      { label: 'follow',       type: 'reaction', price: null,          reactsTo: ['move'],   die: false },
  // combat.tex "Flee": priced by the movement surge it is made with — a
  // reaction to a move, a follow-up to a strike
  flee:        { label: 'flee',         type: 'reaction', price: null,          reactsTo: ['move'],   die: false, identity: { at: null } },
  fleeFollowUp: { label: 'flee',        type: 'action',   price: null,          reactsTo: [],         die: false, generated: true },
  // abilities.tex "Counterattack": a strike of the target's, rolled with the
  // attack it answers and priced by the strike it opens
  counterattack: { label: 'counterattack', type: 'reaction', price: null,      reactsTo: ['strike'], die: true },
  // combat.tex "Grapple Maneuvers": a grapple test against the partner's
  grapple:     { label: 'grapple',      type: 'action',   price: 'grappleManeuver', reactsTo: [],     die: true, targeted: true, identity: { maneuver: 'escape' } },
  // combat.tex "Push and drag": "a force vs force comparison to be able to
  // move", no die, priced by the block declared (rules/drag.ts
  // `getPushPrice`)
  drag:        { label: 'push or drag', noun: 'push',  type: 'action',   price: null,          reactsTo: [],         die: false, targeted: true, movement: true, identity: { pull: false } },
  // letting go of a partner who does not hold back costs nothing
  release:     { label: 'let go',       type: 'action',   price: null,          reactsTo: [],         die: false, targeted: true },
  // gear.tex "Net": a Prestidigitation test against the tether's DL, priced
  // as two standard actions (rules/tether.ts `getSlipCost`)
  slip:        { label: 'slip the net', type: 'action',   price: null,          reactsTo: [],         die: true, targeted: true },
  // gear.tex "Equipment Breakage": a strike at a net's tether, priced by the
  // row it swings
  cut:         { label: 'cut the net',  type: 'action',   price: null,          reactsTo: [],         die: true, targeted: true },
  // combat.tex "Initiate the Grab": "It is possible to grapple back
  // automatically just by having a weapon with grappling property
  // equipped" — one who takes one up mid-grapple does so as a free action
  holdBack:    { label: 'grapple back', type: 'action',   price: null,          reactsTo: [],         die: false, targeted: true },
  // combat.tex "Grapple Maneuvers": the defender's 2 AP + 1 STA that spares
  // them the -5; "Push and drag": the defender's 2 AP for +5
  resist:      { label: 'resist',       type: 'reaction', price: 'grappleDefense', reactsTo: ['grapple', 'drag'], die: false },
  // combat.tex "Push and drag": everyone else in the group may help the
  // push, walking with it ("Use the same rules for multiple characters as
  // grapple"), tag along on neither side, or — held by nobody — let go and
  // leave; against a push each is priced by the block (rules/drag.ts
  // `getPushPrice`)
  assist:      { label: 'help push',    type: 'reaction', price: null,          reactsTo: ['drag'],   die: false, identity: { boost: false } },
  carry:       { label: 'tag along',    type: 'reaction', price: null,          reactsTo: ['drag'],   die: false },
  letGo:       { label: 'let go',       type: 'reaction', price: null,          reactsTo: ['drag'],   die: false },
  // combat.tex "Standard Action"
  pickUp:      { label: 'pick up',      type: 'action',   price: 'standardAction', reactsTo: [],      die: false },
  // combat.tex "Throw", "Standard Action": a held item or one off the
  // floor, to the floor, at its throwing row's price or a standard action's
  throw:       { label: 'throw',        type: 'action',   price: null,          reactsTo: [],         die: false },
  // combat.tex "Rest"
  rest:        { label: 'rest',         type: 'action',   price: 'rest',     reactsTo: [],         die: false },
} as const satisfies { [K in ActionKind]: ActionDef<K> }

// The flags as the catalog declares them, read through the general shape
// where the kind is not known.
export function getActionDef(kind: ActionKind): ActionDef {
  return ACTIONS[kind]
}

export function isReaction(kind: ActionKind): kind is ReactionKind {
  return ACTIONS[kind].type === 'reaction'
}

export function isReactionAction(action: Action): action is ReactionAction {
  return isReaction(action.kind)
}

export function isRootAction(action: Action): action is RootAction {
  return !isReaction(action.kind)
}

// The two weapon attacks, rolled against a defense and landing as an injury.
export function isAttackAction(action: Action): action is AttackAction {
  return action.kind === 'strike' || action.kind === 'shoot'
}

export function reactsTo(kind: ActionKind, root: ActionKind): boolean {
  return (ACTIONS[kind].reactsTo as readonly ActionKind[]).includes(root)
}

export function isDefense(kind: ActionKind): kind is (typeof DEFENSES)[number] {
  return ((DEFENSES satisfies readonly ReactionKind[]) as readonly ActionKind[]).includes(kind)
}
